# Generated by Django 2.1.7 on 2019-03-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(default=1, verbose_name='分类数目'),
        ),
        migrations.AddField(
            model_name='tag',
            name='number',
            field=models.IntegerField(default=1, verbose_name='标签目录'),
        ),
    ]
